FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Fix permissions if needed
RUN chown -R node:node /app
USER node

EXPOSE 3000

CMD ["npm", "run", "dev:docker"]
