version: '3.9'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend-apis:
    build: ./backend-app
    container_name: backend-apis
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      DB_URL: postgresql://admin:secret@postgres-db:5432/myappdb
      USER_DB_URL: postgresql://admin:secret@postgres-db:5432/myappdb
    volumes:
      - ./backend-app:/app
    restart: unless-stopped

volumes:
  pgdata:
