version: '3.9'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - ./database-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend-apis:
    build:
      context: ./backend-apis
      dockerfile: Dockerfile
    container_name: backend-apis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      DB_URL: postgresql://admin:secret@postgres-db:5432/myappdb
    volumes:
      - ./backend-apis/app:/app/app
      - ./backend-apis/.env:/app/.env # Optional, if used
    restart: unless-stopped

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-app:/app
    restart: unless-stopped

volumes:
  pgdata:
